### ISSUE TITLE
OktaInk ExportPrivate question

### ISSUE THREAD

**Issue by FlangvikAD** [CCob/okta-terrify#4]
HI. I am using the tool to export the private key, but I don't know what the pin code is and how to get it? I use windows hello without TPM.

```
OktaInk.exe -o ExportPrivate --pin
```

**Comment by CCob** [comment]
What database format are you working with, legacy or new?

**Comment by FlangvikAD** [comment]
new database format. 

 I exported a ProofOfPossession type certificate.

Also can you tell me if the PIN CODE used for ProofOfPossession encryption is the system PIN CODE that is called or is it generated by Okta Verify itself?

**Comment by FlangvikAD** [comment]
I've learned something about CNG DPAPI, and I think that if the certificate uses a PIN, then the private key properties of the certificate should contain NgcSoftwareKeyPbkdf2Salt

![0](https://github.com/CCob/okta-terrify/assets/112686531/482a2f99-b5b4-444e-bcd3-a095eb2c2ea4)

whereas mine is Createapinprotectedkey, is there any correlation or difference between them?

![1](https://github.com/CCob/okta-terrify/assets/112686531/2e4dd642-15e5-430b-a9d1-8d25fbd74242)

**Comment by CCob** [comment]
Yes that's correct, if a CNG key is protected with a PIN it's used in addition to the user account password + fixed entropy.  Export needs a little more work for the new format as this was implemented recently and haven't had time to look how that affects export functionality.  Hopefully I got some time soon to take a look

**Comment by FlangvikAD** [comment]
I decompiled the program and it looks like the credentials are set via the CreatePinProtectedKeyPair method of the Okta.Devices.SDK.Windows.Native.dll and the passcode is for network transfer? Maybe I can write a dll to hook the CredentialAccessInteraction.GetCredential method to see the passcode.

![0](https://github.com/CCob/okta-terrify/assets/112686531/632b6747-ab9c-47a1-baa4-119fbe9dc87d)

**Comment by CCob** [comment]
I'm going to take a guess that the new DB format will use the same PIN for the software based pop key as it does the TPM backed one.  The only difference under the hood will be which crypto provider it's using to load the key.  

But it's highly doubtful that it will be marked for export, which means you'll need to go the direct route and use the users DPAPI key + PIN + fixed entropy to get at the raw RSA private key from the users AppData folder

**Comment by FlangvikAD** [comment]
After analyzing the code, I think the PIN code it uses is not from the windows system itself, but is transmitted over the network by Okta.

Since it uses SecureString, I can't see the Pincode value in memory for now.

![0](https://github.com/CCob/okta-terrify/assets/112686531/1e480297-765c-4ffe-a76f-7131b7efdb80)

Do you have any ideas on how I can view the actual content of PinCode? Much appreciated.

**Comment by FlangvikAD** [comment]
Also, the certificate was created before I entered the PIN CODE, so at least the PIN CODE used for encryption is not the windows hello pin.
